# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "kernel_module_group")
load("//private/devices/google/common/kleaf:checkpatch.bzl", "checkpatch_strict")

package(
    default_visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

checkpatch_strict(
    name = "checkpatch",
)

filegroup(
    name = "arm-smmu-v3.kconfig",
    srcs = [
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:kconfig",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/perf:kconfig",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

ddk_headers(
    name = "headers",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    visibility = [":__subpackages__"],
)

kernel_module_group(
    name = "arm-smmu-v3",
    srcs = [
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:acfw-debug",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:arm/arm-smmu-v3/arm_smmu_v3",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:arm/arm-smmu-v3/arm_smmu_v3_kvm",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/iommu:io-pgtable-pixel",
        "//private/google-modules/iommu/arm-smmu-v3/drivers/perf:arm_smmuv3_pmu",
    ],
    visibility = [
        "//private/devices/google:__subpackages__",
    ],
)
