# SPDX-License-Identifier: GPL-2.0
#
# Makefile for RPC library
#

NOAH_LIB_PATH := $(ROOT_DIR)/private/google-modules/noa/noah_lib
ccflags-y += -I$(NOAH_LIB_PATH)/pw_rpc_c/public
ccflags-y += -I$(NOAH_LIB_PATH)/gen/pw_rpc_services
ccflags-y += -I$(NOAH_LIB_PATH)/pw_rpc_service_client/public

NANOPB_PATH := $(ROOT_DIR)/private/google-modules/noa/common/nanopb
ccflags-y += -DPB_SYSTEM_HEADER=\"common/pb_linux.h\"
ccflags-y += -I$(NANOPB_PATH)

# For CSP codebase
ifneq ($(wildcard $(ROOT_DIR)/private/google-modules/noa/nanopb),)
ccflags-y += -I$(ROOT_DIR)/private/google-modules/noa/nanopb
endif


DPA_PATH := $(ROOT_DIR)/private/google-modules/dpa
ccflags-y += -I$(DPA_PATH)/include

noa-m += \
	../noah_lib/gen/pw_rpc_services/pw_rpc/echo.pb.o \
	../noah_lib/gen/pw_rpc_services/wlan_rpc_service.pb.o \
	wlan/wlan_rpc_service/wlan_event_rpc_client.o	\
	wlan/wlan_rpc_service/wlan_cmd_rpc_client.o	\
	wlan/wlan_rpc_service/wlan_rpc_call_entry.o	\

noa-m += \
	../noah_lib/gen/pw_rpc_services/pcie_service/pcie_service.pb.o \
	pcie_service/pcie_rpc_client.o		\
	pcie_service/noa_pcie_rpc.o		\

noa-m += \
	../noah_lib/gen/pw_rpc_services/nep_cmd_service.pb.o \
	net/nep_cmd_rpc_service/nep_cmd_rpc_client.o	\
	net/nep_cmd_rpc_service/nep_event_rpc_client.o	\
