# SPDX-License-Identifier: GPL-2.0-or-later

load("@kleaf//build/kernel/kleaf:kernel.bzl", "checkpatch", "ddk_module")

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

ddk_module(
    name = "aoc_ipc",
    srcs = glob(["*.c"]),
    out = "aoc_ipc.ko",
    hdrs = glob(["*.h"]),
    includes = ["."],
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/aoc:__subpackages__",
        "//private/google-modules/touch/common:__subpackages__",
    ],
    deps = [
        "//private/google-modules/aoc:aoc_common_header",
    ],
)
