# SPDX-License-Identifier: GPL-2.0-only

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(
    default_visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/aoc/alsa:__subpackages__",
        "//private/google-modules/power/mitigation:__subpackages__",
        "//private/google-modules/radio/samsung/s5400:__subpackages__",
        "//private/google-modules/soc/gs:__subpackages__",
    ],
)

ddk_module(
    name = "google_modemctl",
    out = "google_modemctl.ko",
    conditional_srcs = {
        "CONFIG_GOOGLE_MODEMCTL": {
            True: [
                "modem_notifier.c",
            ],
        },
    },
    kernel_build = "//private/devices/google/common:kernel",
    visibility = [
        "//private/devices/google:__subpackages__",
        "//private/google-modules/aoc/alsa:__subpackages__",
        "//private/google-modules/power/mitigation:__subpackages__",
        "//private/google-modules/radio/samsung/s5300:__subpackages__",
        "//private/google-modules/radio/samsung/s5400:__subpackages__",
        "//private/google-modules/soc/gs:__subpackages__",
    ],
    deps = [
        "//common:all_headers_aarch64",
        "//private/google-modules/soc/gs:headers",
    ],
)
