# SPDX-License-Identifier: GPL-2.0-or-later

ccflags-y += -I$(srctree)/../../private/google-modules/bms/misc/include \
             -Wno-unknown-pragmas -Wno-format -Wno-unused-variable \
             -Wno-frame-larger-than -DDEBUG

obj-$(CONFIG_GOOGLE_TTF_TEST) += google_ttf_test.o
