# SPDX-License-Identifier: GPL-2.0-or-later

load("@kleaf//build/kernel/kleaf:kernel.bzl", "checkpatch")
load("//private/devices/google/common/kleaf:device_build.bzl", "device_build")
load(":constants.bzl", "MALIBU_DTBS", "MALIBU_MODULE_OUTS")

package(
    default_visibility = [
        "//private/devices/google:__subpackages__",
    ],
)

checkpatch(
    name = "checkpatch",
    checkpatch_pl = "//common:scripts/checkpatch.pl",
)

device_build(
    name = "malibu_base",
    build_configs = ["build.config.malibu"],
    ddk_uapi_headers = [
        # keep sorted
        "//private/google-modules/aoc/alsa:uapi_headers",
        "//private/google-modules/display/common:uapi_headers",
        "//private/google-modules/display/vsi-drm:uapi_headers",
        "//private/google-modules/image/cnm:uapi_headers",
        "//private/google-modules/soc/gs:misc_uapi_headers",
        "//private/google-modules/touch/common:uapi_headers",
        "//private/google-modules/video/cnm:uapi_headers",
    ],
    defconfig_fragments = ["malibu_defconfig"],
    ext_modules = [
        # keep sorted
        "//private/google-modules/amplifiers/audiometrics",
        "//private/google-modules/aoc",
        "//private/google-modules/aoc/alsa",
        "//private/google-modules/aoc/usb:aoc.usb",
        "//private/google-modules/aoc_ipc",
        "//private/google-modules/bms",
        "//private/google-modules/bms:max77779-charger-spmi",
        "//private/google-modules/bms:max77779-fg-spmi",
        "//private/google-modules/bms:max77779-sp-spmi",
        "//private/google-modules/bms:max77779-vimon-spmi",
        "//private/google-modules/bms:max77779_i2cm_spmi",
        "//private/google-modules/bms:max77779_pmic_spmi",
        "//private/google-modules/bms/misc:bms-misc",
        "//private/google-modules/bms/pe26100",
        "//private/google-modules/display/common/gs_drm",
        "//private/google-modules/display/common/gs_panel",
        "//private/google-modules/display/common/panel_tests",
        "//private/google-modules/display/common/panels:panel-gs-simple",
        "//private/google-modules/display/interfaces/synopsys/dwc_dptx",
        "//private/google-modules/display/vsi-drm",
        "//private/google-modules/display/vsi-g2d:drm-g2d",
        "//private/google-modules/dpa:google-dpa.pixel",
        "//private/google-modules/edgetpu/santafe/drivers/edgetpu:edgetpu.santafe",
        "//private/google-modules/gxp/malibu:gxp",
        "//private/google-modules/iif",
        "//private/google-modules/image/cnm",
        "//private/google-modules/iommu/arm-smmu-v3",
        "//private/google-modules/lwis:lwis.erie",
        "//private/google-modules/misc/h2omg",
        "//private/google-modules/misc/sscoredump",
        "//private/google-modules/perf/core/apc_irm:apc_irm_drv",
        "//private/google-modules/perf/core/google_pm_qos",
        "//private/google-modules/perf/core/google_pm_qos:google_vote_manager",
        "//private/google-modules/perf/core/gs_domain_idle",
        "//private/google-modules/perf/core/gs_perf_domain:perf_domain",
        "//private/google-modules/perf/core/gs_perf_mon",
        "//private/google-modules/perf/core/irm_devfreq:google_irm_devfreq",
        "//private/google-modules/perf/core/lat_govs:cmefreq_gov",
        "//private/google-modules/perf/core/lat_govs:gs_governor_dsulat",
        "//private/google-modules/perf/core/lat_govs:gs_governor_memlat",
        "//private/google-modules/perf/core/lat_govs:gs_governor_utils",
        "//private/google-modules/perf/infra/mbfs",
        "//private/google-modules/perf/infra/mbfs:mbfs_cpm_backend",
        "//private/google-modules/perf/thermal",
        "//private/google-modules/power/mitigation:bcl",
        "//private/google-modules/power/mitigation:max77779_bcl_irq",
        "//private/google-modules/power/reset",
        "//private/google-modules/powervr",
        "//private/google-modules/radio/common/metrics_collection",
        "//private/google-modules/soc/gs/drivers/block/zram:zcomp_cpu",
        "//private/google-modules/soc/gs/drivers/block/zram:zram_gs",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:dmabuf-heaps",
        "//private/google-modules/soc/gs/drivers/input:keycombo",
        "//private/google-modules/soc/gs/drivers/input:keydebug",
        "//private/google-modules/soc/gs/drivers/iommu:dma-iommu-vendor-hooks",
        "//private/google-modules/soc/gs/drivers/iommu:iommu_map_benchmark",
        "//private/google-modules/soc/gs/drivers/iommu:samsung-secure-iova",
        "//private/google-modules/soc/gs/drivers/mfd:slg51002-core",
        "//private/google-modules/soc/gs/drivers/misc/sbb-mux:sbb-mux",
        "//private/google-modules/soc/gs/drivers/misc/sscoredump",
        "//private/google-modules/soc/gs/drivers/pinctrl:pinctrl-slg51002",
        "//private/google-modules/soc/gs/drivers/power/reset:debug-reboot",
        "//private/google-modules/soc/gs/drivers/regulator:rt6160-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:s2dos07x02-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:sgm38122-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:sgm38125-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:slg51002-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:sy70206-regulator",
        "//private/google-modules/soc/gs/drivers/regulator:tps628600-regulator",
        "//private/google-modules/soc/gs/drivers/soc/google:hardlockup-watchdog",
        "//private/google-modules/soc/gs/drivers/soc/google:kernel-top",
        "//private/google-modules/soc/gs/drivers/soc/google:perf_trace_counters",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:pixel-debug-test",
        "//private/google-modules/soc/gs/drivers/soc/google/gcma:gcma",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa",
        "//private/google-modules/soc/gs/drivers/soc/google/pa_kill:pa_kill",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_stat:pixel_stat_sysfs",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_stat/mm:pixel_stat_mm",
        "//private/google-modules/soc/gs/drivers/soc/google/pixel_trim",
        "//private/google-modules/soc/gs/drivers/soc/google/smra:smra",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:systrace",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/cgroup:vh_cgroup",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/fs:vh_fs",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/metrics:pixel_metrics",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/mm:vh_mm",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/pixel_em:pixel_em",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:sched_tp",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:vh_preemptirq_long",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:vh_sched",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/thermal:vh_thermal",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:google-role-sw",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:bc_max77759",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:google_tcpci_shim",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77759_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77759_helper",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max77779_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:max777x9_contaminant",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:tcpci_max77759",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:tcpci_max777x9_spmi",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:usb_psy",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:usbc_cooling_dev",
        "//private/google-modules/soc/rdo/aoss-ssr-notifier:aoss_ssr_notifier",
        "//private/google-modules/soc/rdo/ap-pmic:da9188-core",
        "//private/google-modules/soc/rdo/ap-pmic/gpio:da9188-gpio",
        "//private/google-modules/soc/rdo/ap-pmic/regulator:da9188-regulator",
        "//private/google-modules/soc/rdo/ap-pmic/rtc:da9188-rtc",
        "//private/google-modules/soc/rdo/ap-pmic/vgpio:da9188-vgpio",
        "//private/google-modules/soc/rdo/cap-sysfs:google_cap_sysfs",
        "//private/google-modules/soc/rdo/clocksource/google/sst:google_sst",
        "//private/google-modules/soc/rdo/cpu-lpm-stats:google_cpu_lpm_stats",
        "//private/google-modules/soc/rdo/drivers/clk/google:clk-cpm",
        "//private/google-modules/soc/rdo/drivers/dma:google-gpdma",
        "//private/google-modules/soc/rdo/drivers/dma:pl330",
        "//private/google-modules/soc/rdo/drivers/i2c/busses:i2c-designware-core",
        "//private/google-modules/soc/rdo/drivers/i2c/busses:i2c-designware-platform",
        "//private/google-modules/soc/rdo/drivers/i2c/busses/test:i2c-test",
        "//private/google-modules/soc/rdo/drivers/i3c/master:dw-i3c-master",
        "//private/google-modules/soc/rdo/drivers/i3c/master_thi:dw-i3c-master-thi",
        "//private/google-modules/soc/rdo/drivers/i3c/master_thi:dw-i3c-xfer-host-ap",
        "//private/google-modules/soc/rdo/drivers/iis:iis",
        "//private/google-modules/soc/rdo/drivers/input:power_keydebug",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-extended-sysfs",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-gia-google",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-gia-google-test",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-gia-lib",
        "//private/google-modules/soc/rdo/drivers/irqchip:irq-google-cpm",
        "//private/google-modules/soc/rdo/drivers/mailbox:goog-mba-ctrl",
        "//private/google-modules/soc/rdo/drivers/perf:google_gem",
        "//private/google-modules/soc/rdo/drivers/perf:google_gem_test_module",
        "//private/google-modules/soc/rdo/drivers/pinctrl/google:pinctrl",
        "//private/google-modules/soc/rdo/drivers/power:genpd-test-consumer",
        "//private/google-modules/soc/rdo/drivers/rst/google:rst-cpm",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-aoss-wdt-handler",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-chip-info",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-aggr",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-cpm-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-cpm-iface-test",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-doorbell-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-ebu-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-gdmc-iface",
        "//private/google-modules/soc/rdo/drivers/soc/google:goog-mba-gdmc-iface-test",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_gdmc_dhub",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_gtc",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_timestamp_sync",
        "//private/google-modules/soc/rdo/drivers/soc/google:gs-debug-test",
        "//private/google-modules/soc/rdo/drivers/soc/google:pixel-debug-kinfo",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd:gcdd",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd-cpu:goog-cpu-idle-info",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:google-ehld-coreinstr",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:google-skip-s2m-voter",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:towerci",
        "//private/google-modules/soc/rdo/drivers/soc/google/dvfs-helper:dvfs_helper",
        "//private/google-modules/soc/rdo/drivers/soc/google/dvfs-target-frontend:dvfs_target_frontend",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwmt:fwmt",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwtp:fwtp_module_group",
        "//private/google-modules/soc/rdo/drivers/soc/google/lpm-pm-domains:lpm_pm_domains",
        "//private/google-modules/soc/rdo/drivers/soc/google/vdu:gvdu",
        "//private/google-modules/soc/rdo/drivers/spi:spi-dw-mmio",
        "//private/google-modules/soc/rdo/drivers/spmi:regmap-goog-spmi",
        "//private/google-modules/soc/rdo/drivers/spmi:spmi-smartdv",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:google_8250",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:google_8250_base",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:google_8250_dw",
        "//private/google-modules/soc/rdo/drivers/tty/serial/modem-uart:modem-uart",
        "//private/google-modules/soc/rdo/drivers/ufs",
        "//private/google-modules/soc/rdo/ebu:ebu-google",
        "//private/google-modules/soc/rdo/gadget/dta:google_dta",
        "//private/google-modules/soc/rdo/hardlockup-debug:hardlockup-debug",
        "//private/google-modules/soc/rdo/interconnect:google-icc-helper-mock-client",
        "//private/google-modules/soc/rdo/interconnect:google-irm-stub",
        "//private/google-modules/soc/rdo/interconnect:google_icc",
        "//private/google-modules/soc/rdo/interconnect:google_irm",
        "//private/google-modules/soc/rdo/lpcm/gpu:gpu_pf_state",
        "//private/google-modules/soc/rdo/odpm:google_odpm",
        "//private/google-modules/soc/rdo/pci:google-pcie-v2",
        "//private/google-modules/soc/rdo/pci:phy-google-pcie",
        "//private/google-modules/soc/rdo/phy:google-eusb2-repeater",
        "//private/google-modules/soc/rdo/phy:google-usb-phy",
        "//private/google-modules/soc/rdo/power-controller:power_controller",
        "//private/google-modules/soc/rdo/powerdashboard:google_powerdashboard",
        "//private/google-modules/soc/rdo/trace:generic_source",
        "//private/google-modules/soc/rdo/usb:dwc3-google",
        "//private/google-modules/soc/rdo/usb:dwc3-google-aux",
        "//private/google-modules/soc/rdo/watchdog:google_wdt",
        "//private/google-modules/touch/common:touch.common",
        "//private/google-modules/trusty",
        "//private/google-modules/video/cnm",
    ],
    kconfig_exts = ["Kconfig.ext.malibu"],
    kconfigs = [
        # keep sorted
        "//private/google-modules/aoc:aoc.kconfig",
        "//private/google-modules/aoc/alsa:alsa.kconfig",
        "//private/google-modules/aoc/usb:aoc.usb.kconfig",
        "//private/google-modules/bms/misc:bms-misc.kconfig",
        "//private/google-modules/display/common:common.kconfig",
        "//private/google-modules/display/interfaces/synopsys/dwc_dptx:dwc_dptx.kconfig",
        "//private/google-modules/display/vsi-drm:vsi-drm.kconfig",
        "//private/google-modules/display/vsi-g2d:drm-g2d.kconfig",
        "//private/google-modules/iommu/arm-smmu-v3:arm-smmu-v3.kconfig",
        "//private/google-modules/lwis:lwis.kconfig",
        "//private/google-modules/misc/h2omg:h2omg.kconfig",
        "//private/google-modules/perf:perf.kconfig",
        "//private/google-modules/power/mitigation:bcl.kconfig",
        "//private/google-modules/power/reset:reset.kconfig",
        "//private/google-modules/powervr:powervr.kconfig",
        "//private/google-modules/radio/common/metrics_collection:metrics_collection.kconfig",
        "//private/google-modules/soc/gs/drivers/bts:kconfig",
        "//private/google-modules/soc/gs/drivers/char/hw_random:kconfig",
        "//private/google-modules/soc/gs/drivers/clk/gs:kconfig",
        "//private/google-modules/soc/gs/drivers/clocksource:kconfig",
        "//private/google-modules/soc/gs/drivers/cpufreq:kconfig",
        "//private/google-modules/soc/gs/drivers/devfreq-whi/google:kconfig",
        "//private/google-modules/soc/gs/drivers/devfreq/google:kconfig",
        "//private/google-modules/soc/gs/drivers/dma:kconfig",
        "//private/google-modules/soc/gs/drivers/dma-buf/heaps:dmabuf-heaps-kconfig_group",
        "//private/google-modules/soc/gs/drivers/gpu/exynos:kconfig",
        "//private/google-modules/soc/gs/drivers/gpu/exynos/g2d:kconfig",
        "//private/google-modules/soc/gs/drivers/i2c/busses:kconfig",
        "//private/google-modules/soc/gs/drivers/iio:kconfig",
        "//private/google-modules/soc/gs/drivers/iio/power:kconfig",
        "//private/google-modules/soc/gs/drivers/input:kconfig",
        "//private/google-modules/soc/gs/drivers/input/keyboard:kconfig",
        "//private/google-modules/soc/gs/drivers/input/misc:kconfig",
        "//private/google-modules/soc/gs/drivers/input/misc/vl53l1:kconfig",
        "//private/google-modules/soc/gs/drivers/iommu:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos:kconfig",
        "//private/google-modules/soc/gs/drivers/media/platform/exynos/mfc:kconfig",
        "//private/google-modules/soc/gs/drivers/mfd:kconfig",
        "//private/google-modules/soc/gs/drivers/misc:kconfig",
        "//private/google-modules/soc/gs/drivers/misc/sbb-mux:kconfig",
        "//private/google-modules/soc/gs/drivers/misc/sscoredump:sscoredump.kconfig",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc:kconfig",
        "//private/google-modules/soc/gs/drivers/pci/controller/dwc-whi:kconfig",
        "//private/google-modules/soc/gs/drivers/performance/gs_perf_mon:kconfig",
        "//private/google-modules/soc/gs/drivers/performance/lat_governors:kconfig",
        "//private/google-modules/soc/gs/drivers/phy/samsung:kconfig",
        "//private/google-modules/soc/gs/drivers/pinctrl:kconfig",
        "//private/google-modules/soc/gs/drivers/pinctrl/gs:kconfig",
        "//private/google-modules/soc/gs/drivers/power:kconfig",
        "//private/google-modules/soc/gs/drivers/power/reset:kconfig",
        "//private/google-modules/soc/gs/drivers/pwm:kconfig",
        "//private/google-modules/soc/gs/drivers/regulator:kconfig",
        "//private/google-modules/soc/gs/drivers/rtc:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/acpm:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/boot_control:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/debug:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gcma:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gnssif_spi:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/gsa:gsa.kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pa_kill:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pkvm-smc:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/pt:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/s2mpu:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/smra:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel:kconfig",
        "//private/google-modules/soc/gs/drivers/soc/google/vh/kernel/sched:kconfig",
        "//private/google-modules/soc/gs/drivers/spi:kconfig",
        "//private/google-modules/soc/gs/drivers/spmi:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal/google:kconfig",
        "//private/google-modules/soc/gs/drivers/thermal/samsung:kconfig",
        "//private/google-modules/soc/gs/drivers/tty/serial:kconfig",
        "//private/google-modules/soc/gs/drivers/ufs:kconfig",
        "//private/google-modules/soc/gs/drivers/usb:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/dwc3:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/gadget:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/host:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:role-sw.kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm:kconfig",
        "//private/google-modules/soc/gs/drivers/usb/typec/tcpm/google:kconfig",
        "//private/google-modules/soc/gs/drivers/video/backlight:kconfig",
        "//private/google-modules/soc/gs/drivers/watchdog:kconfig",
        "//private/google-modules/soc/rdo:kconfig",
        "//private/google-modules/soc/rdo/aoss-ssr-notifier:kconfig",
        "//private/google-modules/soc/rdo/ap-pmic:kconfig",
        "//private/google-modules/soc/rdo/boot-diary:google_boot_diary.kconfig",
        "//private/google-modules/soc/rdo/cap-sysfs:google_cap_sysfs.kconfig",
        "//private/google-modules/soc/rdo/clk/google:lcm-google.kconfig",
        "//private/google-modules/soc/rdo/clocksource/google/sst:google_sst.kconfig",
        "//private/google-modules/soc/rdo/cpm-cli:google_cpm_cli.kconfig",
        "//private/google-modules/soc/rdo/cpu-lpm-stats:google_cpu_lpm_stats.kconfig",
        "//private/google-modules/soc/rdo/cs-ets:cs-ets.kconfig",
        "//private/google-modules/soc/rdo/cstate-ctrl:cstate-ctrl.kconfig",
        "//private/google-modules/soc/rdo/drivers/clk/google:clk-cpm.kconfig",
        "//private/google-modules/soc/rdo/drivers/dma:google_dma.kconfig",
        "//private/google-modules/soc/rdo/drivers/i2c/busses:kconfig",
        "//private/google-modules/soc/rdo/drivers/i3c/master:kconfig",
        "//private/google-modules/soc/rdo/drivers/i3c/master_thi:kconfig",
        "//private/google-modules/soc/rdo/drivers/iis:iis.kconfig",
        "//private/google-modules/soc/rdo/drivers/input:kconfig",
        "//private/google-modules/soc/rdo/drivers/irqchip:kconfig",
        "//private/google-modules/soc/rdo/drivers/mailbox:kconfig",
        "//private/google-modules/soc/rdo/drivers/perf:kconfig",
        "//private/google-modules/soc/rdo/drivers/pinctrl/google:kconfig",
        "//private/google-modules/soc/rdo/drivers/power:kconfig",
        "//private/google-modules/soc/rdo/drivers/rst/google:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google:soc_google.kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/cdd-cpu:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwmt:kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/fwtp:fwtp.kconfig",
        "//private/google-modules/soc/rdo/drivers/soc/google/vdu:kconfig",
        "//private/google-modules/soc/rdo/drivers/spi:kconfig",
        "//private/google-modules/soc/rdo/drivers/spmi:kconfig",
        "//private/google-modules/soc/rdo/drivers/tty/serial/8250:kconfig",
        "//private/google-modules/soc/rdo/drivers/tty/serial/modem-uart:kconfig",
        "//private/google-modules/soc/rdo/drivers/ufs:ufs.kconfig",
        "//private/google-modules/soc/rdo/ebu:kconfig",
        "//private/google-modules/soc/rdo/edac:kconfig",
        "//private/google-modules/soc/rdo/experimental:kconfig",
        "//private/google-modules/soc/rdo/gadget/dta:kconfig",
        "//private/google-modules/soc/rdo/gadget/perf_test:kconfig",
        "//private/google-modules/soc/rdo/gpca:kconfig",
        "//private/google-modules/soc/rdo/hardlockup-debug:kconfig",
        "//private/google-modules/soc/rdo/interconnect:kconfig",
        "//private/google-modules/soc/rdo/ip-idle-notifier:kconfig",
        "//private/google-modules/soc/rdo/lpcm:kconfig",
        "//private/google-modules/soc/rdo/mem-qos:google-mem-qos.kconfig",
        "//private/google-modules/soc/rdo/odpm:kconfig",
        "//private/google-modules/soc/rdo/pci:Kconfig",
        "//private/google-modules/soc/rdo/phy:kconfig",
        "//private/google-modules/soc/rdo/power-controller:kconfig",
        "//private/google-modules/soc/rdo/powerdashboard:kconfig",
        "//private/google-modules/soc/rdo/pwm:kconfig",
        "//private/google-modules/soc/rdo/soc/google:kconfig",
        "//private/google-modules/soc/rdo/thermal:kconfig",
        "//private/google-modules/soc/rdo/trace:kconfig",
        "//private/google-modules/soc/rdo/usb:kconfig",
        "//private/google-modules/soc/rdo/watchdog:kconfig",
        "//private/google-modules/touch/common:touch.common.kconfig",
        "//private/google-modules/trusty:trusty.kconfig",
        "//private/google-modules/video/cnm:cnm.kconfig",
    ],
    kunit_modules = [
        # keep sorted
        "//private/google-modules/perf/core/apc_irm:apc_irm_test",
        "//private/google-modules/perf/core/gs_domain_idle:gs_domain_idle_kunit_test",
        "//private/google-modules/perf/infra/mbfs:mbfs_api_test",
        "//private/google-modules/perf/infra/mbfs:mbfs_kunit_test",
        "//private/google-modules/perf/thermal:thermal_tests",
        "//private/google-modules/power/mitigation:google_da918x_bcl_test",
        "//private/google-modules/power/mitigation:google_max77779_bcl_irq_test",
        "//private/google-modules/soc/gs/drivers/usb/role-sw:google-role-sw-kunit",
        "//private/google-modules/soc/rdo/drivers/soc/google:google_gdmc_dhub_test_",
        "//private/google-modules/soc/rdo/drivers/soc/google/debug:towerci_test_",
        "//private/google-modules/soc/rdo/drivers/soc/google/vdu:google-vdu-test",
    ],
    system_dlkm_modules_blocklists = ["system_dlkm.blocklist.malibu"],
    vendor_dlkm_modules_blocklists = ["vendor_dlkm.blocklist.malibu"],
    vendor_ramdisk_modules_lists = ["vendor_ramdisk.modules.malibu"],
)

device_build(
    name = "malibu",
    base_device = "malibu_base",
    build_dtb = True,
    build_dtbo = True,
    build_system_dlkm = True,
    build_vendor_dlkm = True,
    build_vendor_kernel_boot = True,
    dtb_outs = MALIBU_DTBS,
    dts_makefile = "dts/Makefile",
    dts_srcs = glob(["dts/**"]) + [
        "//private/google-modules/soc/gs:gs.dt-bindings",
        "//private/google-modules/soc/rdo:rdo.dt-bindings",
    ],
    fs_type = "erofs",
    module_outs = MALIBU_MODULE_OUTS,
)
